package com.vm.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vm.shadowsocks.domain.User;
import com.vm.shadowsocks.domain.History;
import com.vm.shadowsocks.domain.Log;

import com.vm.greendao.db.UserDao;
import com.vm.greendao.db.HistoryDao;
import com.vm.greendao.db.LogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig logDaoConfig;

    private final UserDao userDao;
    private final HistoryDao historyDao;
    private final LogDao logDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        logDaoConfig = daoConfigMap.get(LogDao.class).clone();
        logDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        logDao = new LogDao(logDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(History.class, historyDao);
        registerDao(Log.class, logDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
        logDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public LogDao getLogDao() {
        return logDao;
    }

}
